name: Deploy Theme
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      - uses: TryGhost/action-deploy-theme@v1.5.0
        with:
          api-url: ${{ secrets.GHOST_ADMIN_API_URL }}
          api-key: ${{ secrets.GHOST_ADMIN_API_KEY }}
          exclude:
            - 'assets/svg/ion/*'
            - 'assets/css/*'
            - 'assets/fonts/*'
            - 'assets/video/*'
            - 'package-lock.json'
            - 'yarn.lock'
            - 'gulpfile.js'
          theme-name: 'ggslayley'
          file: 'zip/ggslayley.zip'
