name: Deploy Theme
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@master
      - uses: TryGhost/action-deploy-theme@v1.5.0
        with:
          api-url: ${{ secrets.GHOST_ADMIN_API_URL }}
          api-key: ${{ secrets.GHOST_ADMIN_API_KEY }}
          exclude: 'assets/svg/ion/* assets/css/* assets/scss/* assets/images/* assets/fonts/* assets/video/* zip/* package-lock.json yarn.lock gulpfile.js'
          theme-name: 'ggslayley'
